### ISSUE TITLE
“DateTime?” Type analyze error, or Nullable<T> Type analyze error

### ISSUE THREAD

**Issue by ShangQuX** [newbe36524/Newbe.ObjectVisitor#22]
"DateTime?" Type is "System.Nullable<System.DateTime>".
but Is resolved as a "System.DateTime".
Code：
class Order { public DateTime? CreateDate {get;set;} }

Order o= new Order() { CreateDate = DateTime.Now };
var visitor = o.V();
List<Tuple<string, object>> list = new List<Tuple<string, object>>();
visitor.ForEach(ov => list.Add(new ValueTuple<string, object>(ov.Name, ov.Value))).Run();

**Comment by newbe36524** [comment]
I will take look at it and it is always welcome for you to submit a PR.

**Comment by newbe36524** [comment]
It looks fine. What is your problem?
https://dotnetfiddle.net/CtO8mz

**Comment by ShangQuX** [comment]
I've tried it. It's also a problem in reflection. It shouldn't be your problem
`var type = order.GetType();
 foreach (var pInfo in type.GetProperties())
{
        //PropertyType: Nullable<DateTime>
        var value = pInfo.GetValue(model);
        Console.WriteLine(value.GetType().Name);
        //output: DateTime
}`
