### ISSUE TITLE
是否支持 object 对象的拆箱？

### ISSUE THREAD

**Issue by xingwen1987** [newbe36524/Newbe.ObjectVisitor#23]
入参我使用了 object 对象进行装箱，并传入了对应 object 的类型 T
`private string ObjectInfo<T>(object obj)
        {
            var sb = new StringBuilder();
            var visitor = default(T).V()
                .ForEach((name, value) => sb.Append($"{name}:{value}{Environment.NewLine}"))
                .Cache();
            visitor.Run((T)obj);
            return sb.ToString();
        }`
但是解析结果为空值。

**Comment by newbe36524** [comment]
装箱？那么意思是原来是 struct。这个类库现在不支持 struct。
我推荐你使用最新的 SG 或者 natasha 进行类似的处理

<hr>

嗷，我亲爱的伙伴，非常高兴你关注到了这个仓库，并且进行了一些尝试。
这个仓库仍然处于非常初级的节点。
经过三秒钟慎重的考虑。我会决定归档这个仓库，主要的原因还是在于没有过多的事件维护。
后续我考虑将编写这个仓库代码的经验制作成一些简单的视频或者文章。
再次感谢你的关注。
