### ISSUE TITLE
对值类型的对象，如何进行访问？

### ISSUE THREAD

**Issue by xingwen1987** [newbe36524/Newbe.ObjectVisitor#24]
设置了多个值对象，int、int?、float、float?、double、double?、decimal、decimal?、Guid、Guid?、DateTime、DateTime?、string、class，目前发现只能对 class 进行正常访问。

**Comment by newbe36524** [comment]
是的，你说的没错，目前只支持class

<hr>

嗷，我亲爱的伙伴，非常高兴你关注到了这个仓库，并且进行了一些尝试。
这个仓库仍然处于非常初级的节点。
经过三秒钟慎重的考虑。我会决定归档这个仓库，主要的原因还是在于没有过多的事件维护。
后续我考虑将编写这个仓库代码的经验制作成一些简单的视频或者文章。
再次感谢你的关注。
