### ISSUE TITLE
在 ForEach 方法中定义 Action 时提示：无法将具有语句体的 lambda 表达式转换为表达式树

### ISSUE THREAD

**Issue by xingwen1987** [newbe36524/Newbe.ObjectVisitor#25]
使用说明上的例子：
![image](https://user-images.githubusercontent.com/15207100/132221548-b8642198-3210-4c32-a38c-7713d7dc570c.png)
提示以下异常信息：
![image](https://user-images.githubusercontent.com/15207100/132221464-41777c3a-629c-44df-af1c-4cdd4f3c2855.png)

**Comment by newbe36524** [comment]
是的，不管你是在何处看到的这个文档。我想它已经过时了。实际上应该定义一个静态方法才能 。

<hr>

嗷，我亲爱的伙伴，非常高兴你关注到了这个仓库，并且进行了一些尝试。
这个仓库仍然处于非常初级的节点。
经过三秒钟慎重的考虑。我会决定归档这个仓库，主要的原因还是在于没有过多的事件维护。
后续我考虑将编写这个仓库代码的经验制作成一些简单的视频或者文章。
再次感谢你的关注。
